#!/bin/bash

#host localhost:4001

echo
echo Make sure the previous databases name is changed back to my_database
# make sure the previous database's name is changed back to my_database
curl https://localhost:4001/query -X POST -k -u "l3xrfLfHQfGGZa3UPG46KQ==:6lqNom5jQFa8f43/FcD5xw==" -H "Content-Type: application/json" -d '{
                        "alter_database": "my_new_database",
                        "rename_to": "my_database"
                      }' 
echo
echo make sure previous schemas are cleaned up before examples testing
# make sure previous schemas are cleaned up before examples testing
curl https://localhost:4001/my_database/query -X POST -k -u "l3xrfLfHQfGGZa3UPG46KQ==:6lqNom5jQFa8f43/FcD5xw==" -H "Content-Type: application/json" -d '{
                        "drop_schema": "my_schema",
                        "cascade": true
                      }'
echo
echo make sure the previous alterred schemas are cleaned up before examples testing
# make sure the previous alterred schemas are cleaned up before examples testing
curl https://localhost:4001/my_database/query -X POST -k -u "l3xrfLfHQfGGZa3UPG46KQ==:6lqNom5jQFa8f43/FcD5xw==" -H "Content-Type: application/json" -d '{
                        "drop_schema": "my_new_schema",
                        "cascade": true
                      }'

echo
echo create a plain new schema
# create a plain new schema
curl https://localhost:4001/my_database/query -X POST -k -u "l3xrfLfHQfGGZa3UPG46KQ==:6lqNom5jQFa8f43/FcD5xw==" -H "Content-Type: application/json" -d '{
                        "create_schema": "my_new_schema"
                        }'
